import React from 'react';
import styles from './Policy.module.css'


function PolicyPrivacy() {
  return (
    <div className={styles.policyBlock}> 
        <h1>Polityka prywatności</h1>
        <div className={styles.policyText}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eget aliquet felis, vitae luctus neque. Cras commodo odio et blandit sodales. Morbi euismod tempor neque in tincidunt. Praesent semper euismod velit sed malesuada. Cras interdum eros orci, rhoncus aliquet odio varius sit amet. Nunc volutpat ultricies sapien. Pellentesque elementum urna id lacinia lobortis. Aliquam dignissim imperdiet consectetur. Donec condimentum tincidunt ornare. Duis commodo non sem a mollis. Pellentesque molestie purus eu odio auctor lobortis. Fusce semper tortor id mauris placerat, vel scelerisque magna dictum. Nunc efficitur tempor justo non aliquet. Sed vel sapien interdum, scelerisque metus nec, viverra turpis.</p>
            <p>Nunc placerat congue aliquet. Nulla urna dolor, interdum et facilisis dictum, tristique eget nunc. Ut vel libero sodales, ultricies lectus id, vulputate lacus. Morbi non auctor lorem. Cras at ipsum aliquam, ornare sem nec, auctor magna. Mauris ac lobortis augue. Pellentesque lacinia lacus a nunc mattis, et ultrices nisl porta. Nam sit amet cursus dui, eu mattis neque. Proin viverra tristique nunc, ac interdum neque ultricies ut..</p>
            <p>Maecenas mattis arcu eu eros tincidunt congue. Aliquam sapien enim, volutpat quis nisl sed, ullamcorper congue dui. Donec ullamcorper, dolor et tincidunt faucibus, lectus arcu rutrum nunc, eget condimentum nunc massa eget odio. Duis quam nisi, mollis at volutpat at, posuere ut justo. Pellentesque egestas neque quis diam pulvinar, ut aliquet nulla maximus. Curabitur pellentesque nunc augue, et ultricies justo tristique vel. In sollicitudin, nisi sed tincidunt scelerisque, elit libero pretium lectus, at accumsan tortor ante a purus. Donec non eros mollis, pulvinar nulla quis, suscipit metus. Nulla tincidunt nisi et erat ullamcorper auctor. Aliquam porta tellus vel nibh porta ultricies. Integer pharetra eget leo a semper.</p>
            <p>Nulla facilisi. Integer at purus tempor, sagittis lacus sed, euismod est. Quisque suscipit ultricies ante a tincidunt. Donec et ultrices augue, nec accumsan dolor. Fusce id sodales velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque eu enim dignissim, dictum ligula at, porttitor velit. Vestibulum vitae ante vitae ipsum interdum pretium. Integer molestie tristique risus, sed feugiat nunc semper congue. Cras sed neque et leo ullamcorper tempus. Duis porttitor volutpat semper. In suscipit, nulla at venenatis posuere, nunc quam porta ligula, a fermentum odio nisl consectetur justo. Quisque mollis blandit sem, at sollicitudin elit congue vel. Pellentesque rutrum tellus id lorem rutrum, in mattis justo venenatis.</p>
            <p>Maecenas dictum libero nec ultricies dapibus. Nullam ante libero, eleifend eu ligula accumsan, dapibus ullamcorper enim. Nullam ac lobortis odio. Morbi vitae erat auctor ex sodales tincidunt. Integer sollicitudin suscipit nunc, porttitor lacinia ex sodales eu. Vestibulum varius scelerisque metus ac dignissim. Maecenas ac vulputate diam. Donec pharetra euismod elit, eget dignissim nibh pretium a. Maecenas accumsan aliquam dui id varius. Pellentesque dui lacus, finibus vitae viverra id, aliquam semper turpis. Quisque iaculis vitae nibh eu suscipit. Integer sagittis non purus vel rutrum. Donec ornare eget nulla ac hendrerit. Vestibulum dignissim ex volutpat libero venenatis porttitor. Integer mollis augue nec aliquam faucibus.</p>
        </div>
    </div>
  )
}
export default PolicyPrivacy;